### ISSUE TITLE
[PE-D] UG List command unsuitable line

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W11-1/tp#111]
![Screenshot 2022-04-01 at 2.27.50 PM.png](https://raw.githubusercontent.com/justinekoh/ped/main/files/c6c75579-fe91-428d-b1ed-35f65b034382.png)

This line may be better off in another section that describes the GUI, and will do better with visuals

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: justinekoh/ped#5

**Comment by ongkimlai** [comment]
fixed, added a sample person card image
