### ISSUE TITLE
[PE-D] Find event command fail when input single character for info/

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W11-1/tp#117]
Command used:
- find -e info/s

When find on a single character, the command will fail and the error message does not seem to match the error.

Expected output: Return the list of events with info containing 's'.

![image.png](https://raw.githubusercontent.com/hanhuiice/ped/main/files/c723aea3-a17e-4326-9c63-442b97e07898.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: hanhuiice/ped#1

**Comment by fredtwt** [comment]
fixed! issue was in the regex of information
